-- Create constituencies table with Indian Lok Sabha data
CREATE TABLE public.constituencies (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  state TEXT NOT NULL,
  constituency_number INTEGER NOT NULL,
  constituency_type TEXT NOT NULL DEFAULT 'General',
  total_voters INTEGER DEFAULT 0,
  reserved_category TEXT,
  district TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.constituencies ENABLE ROW LEVEL SECURITY;

-- Allow public read access to constituencies
CREATE POLICY "Constituencies are publicly readable" 
ON public.constituencies 
FOR SELECT 
USING (true);

-- Add email fields to voters table
ALTER TABLE public.voters 
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS email_otp_code TEXT,
ADD COLUMN IF NOT EXISTS email_otp_expires_at TIMESTAMP WITH TIME ZONE;

-- Add constituency_id reference to voters
ALTER TABLE public.voters 
ADD COLUMN IF NOT EXISTS constituency_id UUID REFERENCES public.constituencies(id);

-- Function to get constituencies by state
CREATE OR REPLACE FUNCTION public.get_constituencies_by_state(p_state TEXT)
RETURNS TABLE (
  id UUID,
  name TEXT,
  state TEXT,
  constituency_number INTEGER,
  constituency_type TEXT,
  district TEXT
) 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT c.id, c.name, c.state, c.constituency_number, c.constituency_type, c.district
  FROM public.constituencies c
  WHERE c.state = p_state
  ORDER BY c.constituency_number;
END;
$$;

-- Function to get all unique states
CREATE OR REPLACE FUNCTION public.get_all_states()
RETURNS TABLE (state TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT c.state
  FROM public.constituencies c
  ORDER BY c.state;
END;
$$;

-- Insert Indian Lok Sabha Constituencies (sample data for major states)
INSERT INTO public.constituencies (name, state, constituency_number, constituency_type, district, reserved_category) VALUES
-- Uttar Pradesh (80 seats)
('Saharanpur', 'Uttar Pradesh', 1, 'General', 'Saharanpur', NULL),
('Kairana', 'Uttar Pradesh', 2, 'General', 'Shamli', NULL),
('Muzaffarnagar', 'Uttar Pradesh', 3, 'General', 'Muzaffarnagar', NULL),
('Bijnor', 'Uttar Pradesh', 4, 'General', 'Bijnor', NULL),
('Moradabad', 'Uttar Pradesh', 5, 'General', 'Moradabad', NULL),
('Rampur', 'Uttar Pradesh', 6, 'General', 'Rampur', NULL),
('Sambhal', 'Uttar Pradesh', 7, 'General', 'Sambhal', NULL),
('Amroha', 'Uttar Pradesh', 8, 'General', 'Amroha', NULL),
('Meerut', 'Uttar Pradesh', 9, 'General', 'Meerut', NULL),
('Baghpat', 'Uttar Pradesh', 10, 'General', 'Baghpat', NULL),
('Ghaziabad', 'Uttar Pradesh', 11, 'General', 'Ghaziabad', NULL),
('Gautam Buddha Nagar', 'Uttar Pradesh', 12, 'General', 'Gautam Buddha Nagar', NULL),
('Bulandshahr', 'Uttar Pradesh', 13, 'SC', 'Bulandshahr', 'SC'),
('Aligarh', 'Uttar Pradesh', 14, 'General', 'Aligarh', NULL),
('Hathras', 'Uttar Pradesh', 15, 'SC', 'Hathras', 'SC'),
('Mathura', 'Uttar Pradesh', 16, 'General', 'Mathura', NULL),
('Agra', 'Uttar Pradesh', 17, 'General', 'Agra', NULL),
('Fatehpur Sikri', 'Uttar Pradesh', 18, 'General', 'Agra', NULL),
('Firozabad', 'Uttar Pradesh', 19, 'SC', 'Firozabad', 'SC'),
('Mainpuri', 'Uttar Pradesh', 20, 'General', 'Mainpuri', NULL),
('Etah', 'Uttar Pradesh', 21, 'SC', 'Etah', 'SC'),
('Badaun', 'Uttar Pradesh', 22, 'General', 'Budaun', NULL),
('Aonla', 'Uttar Pradesh', 23, 'General', 'Bareilly', NULL),
('Bareilly', 'Uttar Pradesh', 24, 'General', 'Bareilly', NULL),
('Pilibhit', 'Uttar Pradesh', 25, 'General', 'Pilibhit', NULL),
('Shahjahanpur', 'Uttar Pradesh', 26, 'General', 'Shahjahanpur', NULL),
('Kheri', 'Uttar Pradesh', 27, 'General', 'Lakhimpur Kheri', NULL),
('Hardoi', 'Uttar Pradesh', 28, 'SC', 'Hardoi', 'SC'),
('Misrikh', 'Uttar Pradesh', 29, 'SC', 'Sitapur', 'SC'),
('Unnao', 'Uttar Pradesh', 30, 'General', 'Unnao', NULL),
('Mohanlalganj', 'Uttar Pradesh', 31, 'SC', 'Lucknow', 'SC'),
('Lucknow', 'Uttar Pradesh', 32, 'General', 'Lucknow', NULL),
('Rae Bareli', 'Uttar Pradesh', 33, 'General', 'Rae Bareli', NULL),
('Amethi', 'Uttar Pradesh', 34, 'General', 'Amethi', NULL),
('Sultanpur', 'Uttar Pradesh', 35, 'General', 'Sultanpur', NULL),
('Pratapgarh', 'Uttar Pradesh', 36, 'General', 'Pratapgarh', NULL),
('Farrukhabad', 'Uttar Pradesh', 37, 'General', 'Farrukhabad', NULL),
('Etawah', 'Uttar Pradesh', 38, 'SC', 'Etawah', 'SC'),
('Kannauj', 'Uttar Pradesh', 39, 'General', 'Kannauj', NULL),
('Kanpur', 'Uttar Pradesh', 40, 'General', 'Kanpur', NULL),
('Akbarpur', 'Uttar Pradesh', 41, 'General', 'Kanpur Dehat', NULL),
('Jalaun', 'Uttar Pradesh', 42, 'SC', 'Jalaun', 'SC'),
('Jhansi', 'Uttar Pradesh', 43, 'General', 'Jhansi', NULL),
('Hamirpur', 'Uttar Pradesh', 44, 'General', 'Hamirpur', NULL),
('Banda', 'Uttar Pradesh', 45, 'General', 'Banda', NULL),
('Fatehpur', 'Uttar Pradesh', 46, 'General', 'Fatehpur', NULL),
('Kaushambi', 'Uttar Pradesh', 47, 'SC', 'Kaushambi', 'SC'),
('Phulpur', 'Uttar Pradesh', 48, 'General', 'Allahabad', NULL),
('Allahabad', 'Uttar Pradesh', 49, 'General', 'Allahabad', NULL),
('Barabanki', 'Uttar Pradesh', 50, 'SC', 'Barabanki', 'SC'),
('Faizabad', 'Uttar Pradesh', 51, 'General', 'Faizabad', NULL),
('Ambedkar Nagar', 'Uttar Pradesh', 52, 'SC', 'Ambedkar Nagar', 'SC'),
('Bahraich', 'Uttar Pradesh', 53, 'General', 'Bahraich', NULL),
('Kaiserganj', 'Uttar Pradesh', 54, 'General', 'Bahraich', NULL),
('Shravasti', 'Uttar Pradesh', 55, 'General', 'Shravasti', NULL),
('Gonda', 'Uttar Pradesh', 56, 'General', 'Gonda', NULL),
('Domariyaganj', 'Uttar Pradesh', 57, 'General', 'Siddharthnagar', NULL),
('Basti', 'Uttar Pradesh', 58, 'General', 'Basti', NULL),
('Sant Kabir Nagar', 'Uttar Pradesh', 59, 'General', 'Sant Kabir Nagar', NULL),
('Maharajganj', 'Uttar Pradesh', 60, 'General', 'Maharajganj', NULL),
('Gorakhpur', 'Uttar Pradesh', 61, 'General', 'Gorakhpur', NULL),
('Kushi Nagar', 'Uttar Pradesh', 62, 'SC', 'Kushinagar', 'SC'),
('Deoria', 'Uttar Pradesh', 63, 'General', 'Deoria', NULL),
('Bansgaon', 'Uttar Pradesh', 64, 'SC', 'Gorakhpur', 'SC'),
('Lalganj', 'Uttar Pradesh', 65, 'SC', 'Azamgarh', 'SC'),
('Azamgarh', 'Uttar Pradesh', 66, 'General', 'Azamgarh', NULL),
('Ghosi', 'Uttar Pradesh', 67, 'General', 'Mau', NULL),
('Salempur', 'Uttar Pradesh', 68, 'General', 'Deoria', NULL),
('Ballia', 'Uttar Pradesh', 69, 'General', 'Ballia', NULL),
('Jaunpur', 'Uttar Pradesh', 70, 'General', 'Jaunpur', NULL),
('Machhlishahr', 'Uttar Pradesh', 71, 'SC', 'Jaunpur', 'SC'),
('Ghazipur', 'Uttar Pradesh', 72, 'General', 'Ghazipur', NULL),
('Chandauli', 'Uttar Pradesh', 73, 'General', 'Chandauli', NULL),
('Varanasi', 'Uttar Pradesh', 74, 'General', 'Varanasi', NULL),
('Bhadohi', 'Uttar Pradesh', 75, 'General', 'Sant Ravidas Nagar', NULL),
('Mirzapur', 'Uttar Pradesh', 76, 'General', 'Mirzapur', NULL),
('Robertsganj', 'Uttar Pradesh', 77, 'SC', 'Sonbhadra', 'SC'),
('Sitapur', 'Uttar Pradesh', 78, 'General', 'Sitapur', NULL),
('Dhaurahra', 'Uttar Pradesh', 79, 'General', 'Lakhimpur Kheri', NULL),
('Nagina', 'Uttar Pradesh', 80, 'SC', 'Bijnor', 'SC'),
-- Maharashtra (48 seats)
('Nandurbar', 'Maharashtra', 1, 'ST', 'Nandurbar', 'ST'),
('Dhule', 'Maharashtra', 2, 'General', 'Dhule', NULL),
('Jalgaon', 'Maharashtra', 3, 'General', 'Jalgaon', NULL),
('Raver', 'Maharashtra', 4, 'General', 'Jalgaon', NULL),
('Buldhana', 'Maharashtra', 5, 'General', 'Buldhana', NULL),
('Akola', 'Maharashtra', 6, 'General', 'Akola', NULL),
('Amravati', 'Maharashtra', 7, 'SC', 'Amravati', 'SC'),
('Wardha', 'Maharashtra', 8, 'General', 'Wardha', NULL),
('Ramtek', 'Maharashtra', 9, 'SC', 'Nagpur', 'SC'),
('Nagpur', 'Maharashtra', 10, 'General', 'Nagpur', NULL),
('Bhandara-Gondiya', 'Maharashtra', 11, 'General', 'Bhandara', NULL),
('Gadchiroli-Chimur', 'Maharashtra', 12, 'ST', 'Gadchiroli', 'ST'),
('Chandrapur', 'Maharashtra', 13, 'General', 'Chandrapur', NULL),
('Yavatmal-Washim', 'Maharashtra', 14, 'General', 'Yavatmal', NULL),
('Hingoli', 'Maharashtra', 15, 'General', 'Hingoli', NULL),
('Nanded', 'Maharashtra', 16, 'General', 'Nanded', NULL),
('Parbhani', 'Maharashtra', 17, 'General', 'Parbhani', NULL),
('Jalna', 'Maharashtra', 18, 'General', 'Jalna', NULL),
('Aurangabad', 'Maharashtra', 19, 'General', 'Aurangabad', NULL),
('Dindori', 'Maharashtra', 20, 'ST', 'Nashik', 'ST'),
('Nashik', 'Maharashtra', 21, 'General', 'Nashik', NULL),
('Palghar', 'Maharashtra', 22, 'ST', 'Palghar', 'ST'),
('Bhiwandi', 'Maharashtra', 23, 'General', 'Thane', NULL),
('Kalyan', 'Maharashtra', 24, 'General', 'Thane', NULL),
('Thane', 'Maharashtra', 25, 'General', 'Thane', NULL),
('Mumbai North', 'Maharashtra', 26, 'General', 'Mumbai', NULL),
('Mumbai North-West', 'Maharashtra', 27, 'General', 'Mumbai', NULL),
('Mumbai North-East', 'Maharashtra', 28, 'General', 'Mumbai', NULL),
('Mumbai North-Central', 'Maharashtra', 29, 'General', 'Mumbai', NULL),
('Mumbai South-Central', 'Maharashtra', 30, 'SC', 'Mumbai', 'SC'),
('Mumbai South', 'Maharashtra', 31, 'General', 'Mumbai', NULL),
('Raigad', 'Maharashtra', 32, 'General', 'Raigad', NULL),
('Maval', 'Maharashtra', 33, 'General', 'Pune', NULL),
('Pune', 'Maharashtra', 34, 'General', 'Pune', NULL),
('Baramati', 'Maharashtra', 35, 'General', 'Pune', NULL),
('Shirur', 'Maharashtra', 36, 'General', 'Pune', NULL),
('Ahmednagar', 'Maharashtra', 37, 'General', 'Ahmednagar', NULL),
('Shirdi', 'Maharashtra', 38, 'SC', 'Ahmednagar', 'SC'),
('Beed', 'Maharashtra', 39, 'General', 'Beed', NULL),
('Osmanabad', 'Maharashtra', 40, 'General', 'Osmanabad', NULL),
('Latur', 'Maharashtra', 41, 'SC', 'Latur', 'SC'),
('Solapur', 'Maharashtra', 42, 'SC', 'Solapur', 'SC'),
('Madha', 'Maharashtra', 43, 'General', 'Solapur', NULL),
('Sangli', 'Maharashtra', 44, 'General', 'Sangli', NULL),
('Satara', 'Maharashtra', 45, 'General', 'Satara', NULL),
('Ratnagiri-Sindhudurg', 'Maharashtra', 46, 'General', 'Ratnagiri', NULL),
('Kolhapur', 'Maharashtra', 47, 'General', 'Kolhapur', NULL),
('Hatkanangle', 'Maharashtra', 48, 'SC', 'Kolhapur', 'SC'),
-- West Bengal (42 seats)
('Cooch Behar', 'West Bengal', 1, 'SC', 'Cooch Behar', 'SC'),
('Alipurduars', 'West Bengal', 2, 'ST', 'Alipurduars', 'ST'),
('Jalpaiguri', 'West Bengal', 3, 'SC', 'Jalpaiguri', 'SC'),
('Darjeeling', 'West Bengal', 4, 'General', 'Darjeeling', NULL),
('Raiganj', 'West Bengal', 5, 'General', 'Uttar Dinajpur', NULL),
('Balurghat', 'West Bengal', 6, 'General', 'Dakshin Dinajpur', NULL),
('Maldaha Uttar', 'West Bengal', 7, 'General', 'Malda', NULL),
('Maldaha Dakshin', 'West Bengal', 8, 'General', 'Malda', NULL),
('Jangipur', 'West Bengal', 9, 'General', 'Murshidabad', NULL),
('Baharampur', 'West Bengal', 10, 'General', 'Murshidabad', NULL),
('Murshidabad', 'West Bengal', 11, 'General', 'Murshidabad', NULL),
('Krishnanagar', 'West Bengal', 12, 'General', 'Nadia', NULL),
('Ranaghat', 'West Bengal', 13, 'SC', 'Nadia', 'SC'),
('Bangaon', 'West Bengal', 14, 'SC', 'North 24 Parganas', 'SC'),
('Barrackpore', 'West Bengal', 15, 'General', 'North 24 Parganas', NULL),
('Dum Dum', 'West Bengal', 16, 'General', 'North 24 Parganas', NULL),
('Barasat', 'West Bengal', 17, 'General', 'North 24 Parganas', NULL),
('Basirhat', 'West Bengal', 18, 'General', 'North 24 Parganas', NULL),
('Joynagar', 'West Bengal', 19, 'SC', 'South 24 Parganas', 'SC'),
('Mathurapur', 'West Bengal', 20, 'SC', 'South 24 Parganas', 'SC'),
('Diamond Harbour', 'West Bengal', 21, 'General', 'South 24 Parganas', NULL),
('Jadavpur', 'West Bengal', 22, 'General', 'South 24 Parganas', NULL),
('Kolkata Dakshin', 'West Bengal', 23, 'General', 'Kolkata', NULL),
('Kolkata Uttar', 'West Bengal', 24, 'General', 'Kolkata', NULL),
('Howrah', 'West Bengal', 25, 'General', 'Howrah', NULL),
('Uluberia', 'West Bengal', 26, 'General', 'Howrah', NULL),
('Sreerampur', 'West Bengal', 27, 'General', 'Hooghly', NULL),
('Hooghly', 'West Bengal', 28, 'General', 'Hooghly', NULL),
('Arambag', 'West Bengal', 29, 'SC', 'Hooghly', 'SC'),
('Tamluk', 'West Bengal', 30, 'General', 'Purba Medinipur', NULL),
('Kanthi', 'West Bengal', 31, 'General', 'Purba Medinipur', NULL),
('Ghatal', 'West Bengal', 32, 'General', 'Paschim Medinipur', NULL),
('Jhargram', 'West Bengal', 33, 'ST', 'Jhargram', 'ST'),
('Medinipur', 'West Bengal', 34, 'General', 'Paschim Medinipur', NULL),
('Purulia', 'West Bengal', 35, 'General', 'Purulia', NULL),
('Bankura', 'West Bengal', 36, 'General', 'Bankura', NULL),
('Bishnupur', 'West Bengal', 37, 'SC', 'Bankura', 'SC'),
('Bardhaman Purba', 'West Bengal', 38, 'General', 'Purba Bardhaman', NULL),
('Bardhaman-Durgapur', 'West Bengal', 39, 'General', 'Paschim Bardhaman', NULL),
('Asansol', 'West Bengal', 40, 'General', 'Paschim Bardhaman', NULL),
('Bolpur', 'West Bengal', 41, 'General', 'Birbhum', NULL),
('Birbhum', 'West Bengal', 42, 'General', 'Birbhum', NULL),
-- Tamil Nadu (39 seats)
('Thiruvallur', 'Tamil Nadu', 1, 'SC', 'Thiruvallur', 'SC'),
('Chennai North', 'Tamil Nadu', 2, 'General', 'Chennai', NULL),
('Chennai South', 'Tamil Nadu', 3, 'General', 'Chennai', NULL),
('Chennai Central', 'Tamil Nadu', 4, 'General', 'Chennai', NULL),
('Sriperumbudur', 'Tamil Nadu', 5, 'General', 'Kancheepuram', NULL),
('Kancheepuram', 'Tamil Nadu', 6, 'SC', 'Kancheepuram', 'SC'),
('Arakkonam', 'Tamil Nadu', 7, 'SC', 'Vellore', 'SC'),
('Vellore', 'Tamil Nadu', 8, 'General', 'Vellore', NULL),
('Krishnagiri', 'Tamil Nadu', 9, 'General', 'Krishnagiri', NULL),
('Dharmapuri', 'Tamil Nadu', 10, 'SC', 'Dharmapuri', 'SC'),
('Tiruvannamalai', 'Tamil Nadu', 11, 'General', 'Tiruvannamalai', NULL),
('Arani', 'Tamil Nadu', 12, 'General', 'Tiruvannamalai', NULL),
('Villupuram', 'Tamil Nadu', 13, 'SC', 'Villupuram', 'SC'),
('Kallakurichi', 'Tamil Nadu', 14, 'General', 'Villupuram', NULL),
('Salem', 'Tamil Nadu', 15, 'General', 'Salem', NULL),
('Namakkal', 'Tamil Nadu', 16, 'General', 'Namakkal', NULL),
('Erode', 'Tamil Nadu', 17, 'General', 'Erode', NULL),
('Tiruppur', 'Tamil Nadu', 18, 'General', 'Tiruppur', NULL),
('Nilgiris', 'Tamil Nadu', 19, 'SC', 'Nilgiris', 'SC'),
('Coimbatore', 'Tamil Nadu', 20, 'General', 'Coimbatore', NULL),
('Pollachi', 'Tamil Nadu', 21, 'General', 'Coimbatore', NULL),
('Dindigul', 'Tamil Nadu', 22, 'General', 'Dindigul', NULL),
('Karur', 'Tamil Nadu', 23, 'General', 'Karur', NULL),
('Tiruchirappalli', 'Tamil Nadu', 24, 'General', 'Tiruchirappalli', NULL),
('Perambalur', 'Tamil Nadu', 25, 'SC', 'Perambalur', 'SC'),
('Cuddalore', 'Tamil Nadu', 26, 'General', 'Cuddalore', NULL),
('Chidambaram', 'Tamil Nadu', 27, 'SC', 'Cuddalore', 'SC'),
('Mayiladuthurai', 'Tamil Nadu', 28, 'General', 'Nagapattinam', NULL),
('Nagapattinam', 'Tamil Nadu', 29, 'General', 'Nagapattinam', NULL),
('Thanjavur', 'Tamil Nadu', 30, 'General', 'Thanjavur', NULL),
('Sivaganga', 'Tamil Nadu', 31, 'General', 'Sivaganga', NULL),
('Madurai', 'Tamil Nadu', 32, 'General', 'Madurai', NULL),
('Theni', 'Tamil Nadu', 33, 'General', 'Theni', NULL),
('Virudhunagar', 'Tamil Nadu', 34, 'General', 'Virudhunagar', NULL),
('Ramanathapuram', 'Tamil Nadu', 35, 'General', 'Ramanathapuram', NULL),
('Thoothukkudi', 'Tamil Nadu', 36, 'General', 'Thoothukkudi', NULL),
('Tenkasi', 'Tamil Nadu', 37, 'SC', 'Tirunelveli', 'SC'),
('Tirunelveli', 'Tamil Nadu', 38, 'General', 'Tirunelveli', NULL),
('Kanniyakumari', 'Tamil Nadu', 39, 'General', 'Kanniyakumari', NULL),
-- Karnataka (28 seats)
('Chikkodi', 'Karnataka', 1, 'General', 'Belagavi', NULL),
('Belagavi', 'Karnataka', 2, 'General', 'Belagavi', NULL),
('Bagalkot', 'Karnataka', 3, 'General', 'Bagalkot', NULL),
('Bijapur', 'Karnataka', 4, 'SC', 'Bijapur', 'SC'),
('Kalaburagi', 'Karnataka', 5, 'SC', 'Kalaburagi', 'SC'),
('Raichur', 'Karnataka', 6, 'ST', 'Raichur', 'ST'),
('Bidar', 'Karnataka', 7, 'General', 'Bidar', NULL),
('Koppal', 'Karnataka', 8, 'General', 'Koppal', NULL),
('Bellary', 'Karnataka', 9, 'ST', 'Bellary', 'ST'),
('Haveri', 'Karnataka', 10, 'General', 'Haveri', NULL),
('Dharwad', 'Karnataka', 11, 'General', 'Dharwad', NULL),
('Uttara Kannada', 'Karnataka', 12, 'General', 'Uttara Kannada', NULL),
('Davanagere', 'Karnataka', 13, 'General', 'Davanagere', NULL),
('Shimoga', 'Karnataka', 14, 'General', 'Shimoga', NULL),
('Udupi Chikmagalur', 'Karnataka', 15, 'General', 'Udupi', NULL),
('Hassan', 'Karnataka', 16, 'General', 'Hassan', NULL),
('Dakshina Kannada', 'Karnataka', 17, 'General', 'Dakshina Kannada', NULL),
('Chitradurga', 'Karnataka', 18, 'SC', 'Chitradurga', 'SC'),
('Tumkur', 'Karnataka', 19, 'General', 'Tumkur', NULL),
('Mandya', 'Karnataka', 20, 'General', 'Mandya', NULL),
('Mysore', 'Karnataka', 21, 'General', 'Mysore', NULL),
('Chamarajanagar', 'Karnataka', 22, 'SC', 'Chamarajanagar', 'SC'),
('Bangalore Rural', 'Karnataka', 23, 'General', 'Bangalore Rural', NULL),
('Bangalore North', 'Karnataka', 24, 'General', 'Bangalore', NULL),
('Bangalore Central', 'Karnataka', 25, 'General', 'Bangalore', NULL),
('Bangalore South', 'Karnataka', 26, 'General', 'Bangalore', NULL),
('Chikkaballapur', 'Karnataka', 27, 'SC', 'Chikkaballapur', 'SC'),
('Kolar', 'Karnataka', 28, 'SC', 'Kolar', 'SC'),
-- Gujarat (26 seats)
('Kachchh', 'Gujarat', 1, 'General', 'Kachchh', NULL),
('Banaskantha', 'Gujarat', 2, 'General', 'Banaskantha', NULL),
('Patan', 'Gujarat', 3, 'SC', 'Patan', 'SC'),
('Mahesana', 'Gujarat', 4, 'General', 'Mahesana', NULL),
('Sabarkantha', 'Gujarat', 5, 'General', 'Sabarkantha', NULL),
('Gandhinagar', 'Gujarat', 6, 'General', 'Gandhinagar', NULL),
('Ahmedabad East', 'Gujarat', 7, 'General', 'Ahmedabad', NULL),
('Ahmedabad West', 'Gujarat', 8, 'General', 'Ahmedabad', NULL),
('Surendranagar', 'Gujarat', 9, 'General', 'Surendranagar', NULL),
('Rajkot', 'Gujarat', 10, 'General', 'Rajkot', NULL),
('Porbandar', 'Gujarat', 11, 'General', 'Porbandar', NULL),
('Jamnagar', 'Gujarat', 12, 'General', 'Jamnagar', NULL),
('Junagadh', 'Gujarat', 13, 'General', 'Junagadh', NULL),
('Amreli', 'Gujarat', 14, 'General', 'Amreli', NULL),
('Bhavnagar', 'Gujarat', 15, 'General', 'Bhavnagar', NULL),
('Anand', 'Gujarat', 16, 'General', 'Anand', NULL),
('Kheda', 'Gujarat', 17, 'General', 'Kheda', NULL),
('Panchmahal', 'Gujarat', 18, 'General', 'Panchmahal', NULL),
('Dahod', 'Gujarat', 19, 'ST', 'Dahod', 'ST'),
('Vadodara', 'Gujarat', 20, 'General', 'Vadodara', NULL),
('Chhota Udaipur', 'Gujarat', 21, 'ST', 'Chhota Udaipur', 'ST'),
('Bharuch', 'Gujarat', 22, 'General', 'Bharuch', NULL),
('Bardoli', 'Gujarat', 23, 'ST', 'Surat', 'ST'),
('Surat', 'Gujarat', 24, 'General', 'Surat', NULL),
('Navsari', 'Gujarat', 25, 'General', 'Navsari', NULL),
('Valsad', 'Gujarat', 26, 'ST', 'Valsad', 'ST'),
-- Rajasthan (25 seats)
('Ganganagar', 'Rajasthan', 1, 'General', 'Ganganagar', NULL),
('Bikaner', 'Rajasthan', 2, 'General', 'Bikaner', NULL),
('Churu', 'Rajasthan', 3, 'General', 'Churu', NULL),
('Jhunjhunu', 'Rajasthan', 4, 'General', 'Jhunjhunu', NULL),
('Sikar', 'Rajasthan', 5, 'General', 'Sikar', NULL),
('Jaipur Rural', 'Rajasthan', 6, 'General', 'Jaipur', NULL),
('Jaipur', 'Rajasthan', 7, 'General', 'Jaipur', NULL),
('Alwar', 'Rajasthan', 8, 'General', 'Alwar', NULL),
('Bharatpur', 'Rajasthan', 9, 'SC', 'Bharatpur', 'SC'),
('Karauli-Dholpur', 'Rajasthan', 10, 'SC', 'Karauli', 'SC'),
('Dausa', 'Rajasthan', 11, 'ST', 'Dausa', 'ST'),
('Tonk-Sawai Madhopur', 'Rajasthan', 12, 'General', 'Tonk', NULL),
('Ajmer', 'Rajasthan', 13, 'General', 'Ajmer', NULL),
('Nagaur', 'Rajasthan', 14, 'General', 'Nagaur', NULL),
('Pali', 'Rajasthan', 15, 'General', 'Pali', NULL),
('Jodhpur', 'Rajasthan', 16, 'General', 'Jodhpur', NULL),
('Barmer', 'Rajasthan', 17, 'General', 'Barmer', NULL),
('Jalore', 'Rajasthan', 18, 'General', 'Jalore', NULL),
('Udaipur', 'Rajasthan', 19, 'ST', 'Udaipur', 'ST'),
('Banswara', 'Rajasthan', 20, 'ST', 'Banswara', 'ST'),
('Chittorgarh', 'Rajasthan', 21, 'General', 'Chittorgarh', NULL),
('Rajsamand', 'Rajasthan', 22, 'General', 'Rajsamand', NULL),
('Bhilwara', 'Rajasthan', 23, 'General', 'Bhilwara', NULL),
('Kota', 'Rajasthan', 24, 'General', 'Kota', NULL),
('Jhalawar-Baran', 'Rajasthan', 25, 'General', 'Jhalawar', NULL),
-- Bihar (40 seats)
('Valmiki Nagar', 'Bihar', 1, 'General', 'West Champaran', NULL),
('Paschim Champaran', 'Bihar', 2, 'SC', 'West Champaran', 'SC'),
('Purvi Champaran', 'Bihar', 3, 'General', 'East Champaran', NULL),
('Sheohar', 'Bihar', 4, 'General', 'Sheohar', NULL),
('Sitamarhi', 'Bihar', 5, 'General', 'Sitamarhi', NULL),
('Madhubani', 'Bihar', 6, 'General', 'Madhubani', NULL),
('Jhanjharpur', 'Bihar', 7, 'General', 'Madhubani', NULL),
('Supaul', 'Bihar', 8, 'General', 'Supaul', NULL),
('Araria', 'Bihar', 9, 'General', 'Araria', NULL),
('Kishanganj', 'Bihar', 10, 'General', 'Kishanganj', NULL),
('Katihar', 'Bihar', 11, 'General', 'Katihar', NULL),
('Purnia', 'Bihar', 12, 'General', 'Purnia', NULL),
('Madhepura', 'Bihar', 13, 'General', 'Madhepura', NULL),
('Darbhanga', 'Bihar', 14, 'General', 'Darbhanga', NULL),
('Muzaffarpur', 'Bihar', 15, 'General', 'Muzaffarpur', NULL),
('Vaishali', 'Bihar', 16, 'SC', 'Vaishali', 'SC'),
('Gopalganj', 'Bihar', 17, 'SC', 'Gopalganj', 'SC'),
('Siwan', 'Bihar', 18, 'General', 'Siwan', NULL),
('Maharajganj', 'Bihar', 19, 'General', 'Siwan', NULL),
('Saran', 'Bihar', 20, 'General', 'Saran', NULL),
('Hajipur', 'Bihar', 21, 'SC', 'Vaishali', 'SC'),
('Ujiarpur', 'Bihar', 22, 'General', 'Samastipur', NULL),
('Samastipur', 'Bihar', 23, 'SC', 'Samastipur', 'SC'),
('Begusarai', 'Bihar', 24, 'General', 'Begusarai', NULL),
('Khagaria', 'Bihar', 25, 'General', 'Khagaria', NULL),
('Bhagalpur', 'Bihar', 26, 'General', 'Bhagalpur', NULL),
('Banka', 'Bihar', 27, 'General', 'Banka', NULL),
('Munger', 'Bihar', 28, 'General', 'Munger', NULL),
('Nalanda', 'Bihar', 29, 'General', 'Nalanda', NULL),
('Patna Sahib', 'Bihar', 30, 'General', 'Patna', NULL),
('Pataliputra', 'Bihar', 31, 'General', 'Patna', NULL),
('Arrah', 'Bihar', 32, 'General', 'Bhojpur', NULL),
('Buxar', 'Bihar', 33, 'General', 'Buxar', NULL),
('Sasaram', 'Bihar', 34, 'SC', 'Rohtas', 'SC'),
('Karakat', 'Bihar', 35, 'General', 'Rohtas', NULL),
('Jahanabad', 'Bihar', 36, 'General', 'Jahanabad', NULL),
('Aurangabad', 'Bihar', 37, 'General', 'Aurangabad', NULL),
('Gaya', 'Bihar', 38, 'SC', 'Gaya', 'SC'),
('Nawada', 'Bihar', 39, 'General', 'Nawada', NULL),
('Jamui', 'Bihar', 40, 'SC', 'Jamui', 'SC'),
-- Madhya Pradesh (29 seats)
('Morena', 'Madhya Pradesh', 1, 'General', 'Morena', NULL),
('Bhind', 'Madhya Pradesh', 2, 'General', 'Bhind', NULL),
('Gwalior', 'Madhya Pradesh', 3, 'General', 'Gwalior', NULL),
('Guna', 'Madhya Pradesh', 4, 'General', 'Guna', NULL),
('Sagar', 'Madhya Pradesh', 5, 'General', 'Sagar', NULL),
('Tikamgarh', 'Madhya Pradesh', 6, 'SC', 'Tikamgarh', 'SC'),
('Damoh', 'Madhya Pradesh', 7, 'General', 'Damoh', NULL),
('Khajuraho', 'Madhya Pradesh', 8, 'General', 'Chhatarpur', NULL),
('Satna', 'Madhya Pradesh', 9, 'General', 'Satna', NULL),
('Rewa', 'Madhya Pradesh', 10, 'General', 'Rewa', NULL),
('Sidhi', 'Madhya Pradesh', 11, 'General', 'Sidhi', NULL),
('Shahdol', 'Madhya Pradesh', 12, 'ST', 'Shahdol', 'ST'),
('Jabalpur', 'Madhya Pradesh', 13, 'General', 'Jabalpur', NULL),
('Mandla', 'Madhya Pradesh', 14, 'ST', 'Mandla', 'ST'),
('Balaghat', 'Madhya Pradesh', 15, 'General', 'Balaghat', NULL),
('Chhindwara', 'Madhya Pradesh', 16, 'General', 'Chhindwara', NULL),
('Hoshangabad', 'Madhya Pradesh', 17, 'General', 'Hoshangabad', NULL),
('Vidisha', 'Madhya Pradesh', 18, 'General', 'Vidisha', NULL),
('Bhopal', 'Madhya Pradesh', 19, 'General', 'Bhopal', NULL),
('Rajgarh', 'Madhya Pradesh', 20, 'General', 'Rajgarh', NULL),
('Dewas', 'Madhya Pradesh', 21, 'SC', 'Dewas', 'SC'),
('Ujjain', 'Madhya Pradesh', 22, 'General', 'Ujjain', NULL),
('Mandsaur', 'Madhya Pradesh', 23, 'General', 'Mandsaur', NULL),
('Ratlam', 'Madhya Pradesh', 24, 'ST', 'Ratlam', 'ST'),
('Dhar', 'Madhya Pradesh', 25, 'ST', 'Dhar', 'ST'),
('Indore', 'Madhya Pradesh', 26, 'General', 'Indore', NULL),
('Khargone', 'Madhya Pradesh', 27, 'ST', 'Khargone', 'ST'),
('Khandwa', 'Madhya Pradesh', 28, 'General', 'East Nimar', NULL),
('Betul', 'Madhya Pradesh', 29, 'ST', 'Betul', 'ST'),
-- Andhra Pradesh (25 seats)
('Araku', 'Andhra Pradesh', 1, 'ST', 'Visakhapatnam', 'ST'),
('Srikakulam', 'Andhra Pradesh', 2, 'General', 'Srikakulam', NULL),
('Vizianagaram', 'Andhra Pradesh', 3, 'General', 'Vizianagaram', NULL),
('Visakhapatnam', 'Andhra Pradesh', 4, 'General', 'Visakhapatnam', NULL),
('Anakapalli', 'Andhra Pradesh', 5, 'General', 'Visakhapatnam', NULL),
('Kakinada', 'Andhra Pradesh', 6, 'General', 'East Godavari', NULL),
('Amalapuram', 'Andhra Pradesh', 7, 'SC', 'East Godavari', 'SC'),
('Rajahmundry', 'Andhra Pradesh', 8, 'General', 'East Godavari', NULL),
('Narasapuram', 'Andhra Pradesh', 9, 'General', 'West Godavari', NULL),
('Eluru', 'Andhra Pradesh', 10, 'General', 'West Godavari', NULL),
('Machilipatnam', 'Andhra Pradesh', 11, 'SC', 'Krishna', 'SC'),
('Vijayawada', 'Andhra Pradesh', 12, 'General', 'Krishna', NULL),
('Guntur', 'Andhra Pradesh', 13, 'General', 'Guntur', NULL),
('Narasaraopet', 'Andhra Pradesh', 14, 'General', 'Guntur', NULL),
('Bapatla', 'Andhra Pradesh', 15, 'SC', 'Guntur', 'SC'),
('Ongole', 'Andhra Pradesh', 16, 'General', 'Prakasam', NULL),
('Nandyal', 'Andhra Pradesh', 17, 'General', 'Kurnool', NULL),
('Kurnool', 'Andhra Pradesh', 18, 'General', 'Kurnool', NULL),
('Anantapur', 'Andhra Pradesh', 19, 'General', 'Anantapur', NULL),
('Hindupur', 'Andhra Pradesh', 20, 'General', 'Anantapur', NULL),
('Kadapa', 'Andhra Pradesh', 21, 'General', 'YSR Kadapa', NULL),
('Nellore', 'Andhra Pradesh', 22, 'General', 'Nellore', NULL),
('Tirupati', 'Andhra Pradesh', 23, 'SC', 'Chittoor', 'SC'),
('Rajampet', 'Andhra Pradesh', 24, 'General', 'YSR Kadapa', NULL),
('Chittoor', 'Andhra Pradesh', 25, 'General', 'Chittoor', NULL),
-- Delhi (7 seats)
('Chandni Chowk', 'Delhi', 1, 'General', 'Central Delhi', NULL),
('North East Delhi', 'Delhi', 2, 'General', 'North East Delhi', NULL),
('East Delhi', 'Delhi', 3, 'General', 'East Delhi', NULL),
('New Delhi', 'Delhi', 4, 'General', 'New Delhi', NULL),
('North West Delhi', 'Delhi', 5, 'SC', 'North West Delhi', 'SC'),
('West Delhi', 'Delhi', 6, 'General', 'West Delhi', NULL),
('South Delhi', 'Delhi', 7, 'General', 'South Delhi', NULL),
-- Kerala (20 seats)
('Kasaragod', 'Kerala', 1, 'General', 'Kasaragod', NULL),
('Kannur', 'Kerala', 2, 'General', 'Kannur', NULL),
('Vatakara', 'Kerala', 3, 'General', 'Kozhikode', NULL),
('Wayanad', 'Kerala', 4, 'General', 'Wayanad', NULL),
('Kozhikode', 'Kerala', 5, 'General', 'Kozhikode', NULL),
('Malappuram', 'Kerala', 6, 'General', 'Malappuram', NULL),
('Ponnani', 'Kerala', 7, 'General', 'Malappuram', NULL),
('Palakkad', 'Kerala', 8, 'General', 'Palakkad', NULL),
('Alathur', 'Kerala', 9, 'SC', 'Palakkad', 'SC'),
('Thrissur', 'Kerala', 10, 'General', 'Thrissur', NULL),
('Chalakudy', 'Kerala', 11, 'General', 'Thrissur', NULL),
('Ernakulam', 'Kerala', 12, 'General', 'Ernakulam', NULL),
('Idukki', 'Kerala', 13, 'General', 'Idukki', NULL),
('Kottayam', 'Kerala', 14, 'General', 'Kottayam', NULL),
('Alappuzha', 'Kerala', 15, 'General', 'Alappuzha', NULL),
('Mavelikkara', 'Kerala', 16, 'SC', 'Alappuzha', 'SC'),
('Pathanamthitta', 'Kerala', 17, 'General', 'Pathanamthitta', NULL),
('Kollam', 'Kerala', 18, 'General', 'Kollam', NULL),
('Attingal', 'Kerala', 19, 'General', 'Thiruvananthapuram', NULL),
('Thiruvananthapuram', 'Kerala', 20, 'General', 'Thiruvananthapuram', NULL),
-- Telangana (17 seats)
('Adilabad', 'Telangana', 1, 'ST', 'Adilabad', 'ST'),
('Peddapalle', 'Telangana', 2, 'SC', 'Peddapalle', 'SC'),
('Karimnagar', 'Telangana', 3, 'General', 'Karimnagar', NULL),
('Nizamabad', 'Telangana', 4, 'General', 'Nizamabad', NULL),
('Zahirabad', 'Telangana', 5, 'SC', 'Medak', 'SC'),
('Medak', 'Telangana', 6, 'General', 'Medak', NULL),
('Malkajgiri', 'Telangana', 7, 'General', 'Medchal', NULL),
('Secunderabad', 'Telangana', 8, 'General', 'Hyderabad', NULL),
('Hyderabad', 'Telangana', 9, 'General', 'Hyderabad', NULL),
('Chevella', 'Telangana', 10, 'SC', 'Rangareddy', 'SC'),
('Mahbubnagar', 'Telangana', 11, 'General', 'Mahbubnagar', NULL),
('Nagarkurnool', 'Telangana', 12, 'SC', 'Nagarkurnool', 'SC'),
('Nalgonda', 'Telangana', 13, 'General', 'Nalgonda', NULL),
('Bhongir', 'Telangana', 14, 'General', 'Yadadri Bhongir', NULL),
('Warangal', 'Telangana', 15, 'SC', 'Warangal', 'SC'),
('Mahabubabad', 'Telangana', 16, 'ST', 'Mahabubabad', 'ST'),
('Khammam', 'Telangana', 17, 'General', 'Khammam', NULL),
-- Odisha (21 seats)
('Bargarh', 'Odisha', 1, 'General', 'Bargarh', NULL),
('Sundargarh', 'Odisha', 2, 'ST', 'Sundargarh', 'ST'),
('Sambalpur', 'Odisha', 3, 'General', 'Sambalpur', NULL),
('Keonjhar', 'Odisha', 4, 'ST', 'Keonjhar', 'ST'),
('Mayurbhanj', 'Odisha', 5, 'ST', 'Mayurbhanj', 'ST'),
('Balasore', 'Odisha', 6, 'General', 'Balasore', NULL),
('Bhadrak', 'Odisha', 7, 'SC', 'Bhadrak', 'SC'),
('Jajpur', 'Odisha', 8, 'SC', 'Jajpur', 'SC'),
('Dhenkanal', 'Odisha', 9, 'General', 'Dhenkanal', NULL),
('Bolangir', 'Odisha', 10, 'General', 'Bolangir', NULL),
('Kalahandi', 'Odisha', 11, 'General', 'Kalahandi', NULL),
('Nabarangpur', 'Odisha', 12, 'ST', 'Nabarangpur', 'ST'),
('Kandhamal', 'Odisha', 13, 'SC', 'Kandhamal', 'SC'),
('Cuttack', 'Odisha', 14, 'General', 'Cuttack', NULL),
('Kendrapara', 'Odisha', 15, 'General', 'Kendrapara', NULL),
('Jagatsinghpur', 'Odisha', 16, 'SC', 'Jagatsinghpur', 'SC'),
('Puri', 'Odisha', 17, 'General', 'Puri', NULL),
('Bhubaneswar', 'Odisha', 18, 'General', 'Khorda', NULL),
('Aska', 'Odisha', 19, 'General', 'Ganjam', NULL),
('Berhampur', 'Odisha', 20, 'SC', 'Ganjam', 'SC'),
('Koraput', 'Odisha', 21, 'ST', 'Koraput', 'ST'),
-- Punjab (13 seats)
('Gurdaspur', 'Punjab', 1, 'General', 'Gurdaspur', NULL),
('Amritsar', 'Punjab', 2, 'General', 'Amritsar', NULL),
('Khadoor Sahib', 'Punjab', 3, 'General', 'Tarn Taran', NULL),
('Jalandhar', 'Punjab', 4, 'SC', 'Jalandhar', 'SC'),
('Hoshiarpur', 'Punjab', 5, 'SC', 'Hoshiarpur', 'SC'),
('Anandpur Sahib', 'Punjab', 6, 'General', 'Rupnagar', NULL),
('Ludhiana', 'Punjab', 7, 'General', 'Ludhiana', NULL),
('Fatehgarh Sahib', 'Punjab', 8, 'SC', 'Fatehgarh Sahib', 'SC'),
('Faridkot', 'Punjab', 9, 'SC', 'Faridkot', 'SC'),
('Firozpur', 'Punjab', 10, 'General', 'Firozpur', NULL),
('Bathinda', 'Punjab', 11, 'General', 'Bathinda', NULL),
('Sangrur', 'Punjab', 12, 'General', 'Sangrur', NULL),
('Patiala', 'Punjab', 13, 'General', 'Patiala', NULL),
-- Jharkhand (14 seats)
('Rajmahal', 'Jharkhand', 1, 'ST', 'Sahibganj', 'ST'),
('Dumka', 'Jharkhand', 2, 'ST', 'Dumka', 'ST'),
('Godda', 'Jharkhand', 3, 'General', 'Godda', NULL),
('Chatra', 'Jharkhand', 4, 'General', 'Chatra', NULL),
('Kodarma', 'Jharkhand', 5, 'General', 'Kodarma', NULL),
('Giridih', 'Jharkhand', 6, 'General', 'Giridih', NULL),
('Dhanbad', 'Jharkhand', 7, 'General', 'Dhanbad', NULL),
('Ranchi', 'Jharkhand', 8, 'General', 'Ranchi', NULL),
('Jamshedpur', 'Jharkhand', 9, 'General', 'East Singhbhum', NULL),
('Singhbhum', 'Jharkhand', 10, 'ST', 'West Singhbhum', 'ST'),
('Khunti', 'Jharkhand', 11, 'ST', 'Khunti', 'ST'),
('Lohardaga', 'Jharkhand', 12, 'ST', 'Lohardaga', 'ST'),
('Palamu', 'Jharkhand', 13, 'SC', 'Palamu', 'SC'),
('Hazaribagh', 'Jharkhand', 14, 'General', 'Hazaribagh', NULL),
-- Assam (14 seats)
('Kokrajhar', 'Assam', 1, 'ST', 'Kokrajhar', 'ST'),
('Dhubri', 'Assam', 2, 'General', 'Dhubri', NULL),
('Barpeta', 'Assam', 3, 'General', 'Barpeta', NULL),
('Gauhati', 'Assam', 4, 'General', 'Kamrup', NULL),
('Mangaldoi', 'Assam', 5, 'General', 'Darrang', NULL),
('Tezpur', 'Assam', 6, 'General', 'Sonitpur', NULL),
('Nowgong', 'Assam', 7, 'General', 'Nagaon', NULL),
('Kaliabor', 'Assam', 8, 'General', 'Nagaon', NULL),
('Jorhat', 'Assam', 9, 'General', 'Jorhat', NULL),
('Dibrugarh', 'Assam', 10, 'General', 'Dibrugarh', NULL),
('Lakhimpur', 'Assam', 11, 'General', 'Lakhimpur', NULL),
('Autonomous District', 'Assam', 12, 'ST', 'Karbi Anglong', 'ST'),
('Silchar', 'Assam', 13, 'General', 'Cachar', NULL),
('Karimganj', 'Assam', 14, 'SC', 'Karimganj', 'SC'),
-- Haryana (10 seats)
('Ambala', 'Haryana', 1, 'SC', 'Ambala', 'SC'),
('Kurukshetra', 'Haryana', 2, 'General', 'Kurukshetra', NULL),
('Sirsa', 'Haryana', 3, 'General', 'Sirsa', NULL),
('Hisar', 'Haryana', 4, 'General', 'Hisar', NULL),
('Karnal', 'Haryana', 5, 'General', 'Karnal', NULL),
('Sonipat', 'Haryana', 6, 'General', 'Sonipat', NULL),
('Rohtak', 'Haryana', 7, 'General', 'Rohtak', NULL),
('Bhiwani-Mahendragarh', 'Haryana', 8, 'General', 'Bhiwani', NULL),
('Gurgaon', 'Haryana', 9, 'General', 'Gurgaon', NULL),
('Faridabad', 'Haryana', 10, 'General', 'Faridabad', NULL),
-- Chhattisgarh (11 seats)
('Sarguja', 'Chhattisgarh', 1, 'ST', 'Sarguja', 'ST'),
('Raigarh', 'Chhattisgarh', 2, 'ST', 'Raigarh', 'ST'),
('Janjgir-Champa', 'Chhattisgarh', 3, 'SC', 'Janjgir-Champa', 'SC'),
('Korba', 'Chhattisgarh', 4, 'ST', 'Korba', 'ST'),
('Bilaspur', 'Chhattisgarh', 5, 'General', 'Bilaspur', NULL),
('Rajnandgaon', 'Chhattisgarh', 6, 'General', 'Rajnandgaon', NULL),
('Durg', 'Chhattisgarh', 7, 'General', 'Durg', NULL),
('Raipur', 'Chhattisgarh', 8, 'General', 'Raipur', NULL),
('Mahasamund', 'Chhattisgarh', 9, 'SC', 'Mahasamund', 'SC'),
('Bastar', 'Chhattisgarh', 10, 'ST', 'Bastar', 'ST'),
('Kanker', 'Chhattisgarh', 11, 'ST', 'Kanker', 'ST'),
-- Uttarakhand (5 seats)
('Tehri Garhwal', 'Uttarakhand', 1, 'General', 'Tehri Garhwal', NULL),
('Pauri Garhwal', 'Uttarakhand', 2, 'General', 'Pauri Garhwal', NULL),
('Almora', 'Uttarakhand', 3, 'General', 'Almora', NULL),
('Nainital-Udhamsingh Nagar', 'Uttarakhand', 4, 'General', 'Nainital', NULL),
('Haridwar', 'Uttarakhand', 5, 'SC', 'Haridwar', 'SC'),
-- Himachal Pradesh (4 seats)
('Kangra', 'Himachal Pradesh', 1, 'General', 'Kangra', NULL),
('Mandi', 'Himachal Pradesh', 2, 'General', 'Mandi', NULL),
('Hamirpur', 'Himachal Pradesh', 3, 'General', 'Hamirpur', NULL),
('Shimla', 'Himachal Pradesh', 4, 'SC', 'Shimla', 'SC'),
-- Jammu and Kashmir (5 seats)
('Baramulla', 'Jammu and Kashmir', 1, 'General', 'Baramulla', NULL),
('Srinagar', 'Jammu and Kashmir', 2, 'General', 'Srinagar', NULL),
('Anantnag-Rajouri', 'Jammu and Kashmir', 3, 'General', 'Anantnag', NULL),
('Udhampur', 'Jammu and Kashmir', 4, 'General', 'Udhampur', NULL),
('Jammu', 'Jammu and Kashmir', 5, 'General', 'Jammu', NULL),
-- Goa (2 seats)
('North Goa', 'Goa', 1, 'General', 'North Goa', NULL),
('South Goa', 'Goa', 2, 'General', 'South Goa', NULL),
-- Tripura (2 seats)
('Tripura West', 'Tripura', 1, 'General', 'West Tripura', NULL),
('Tripura East', 'Tripura', 2, 'ST', 'Dhalai', 'ST'),
-- Meghalaya (2 seats)
('Shillong', 'Meghalaya', 1, 'General', 'East Khasi Hills', NULL),
('Tura', 'Meghalaya', 2, 'ST', 'West Garo Hills', 'ST'),
-- Manipur (2 seats)
('Inner Manipur', 'Manipur', 1, 'General', 'Imphal East', NULL),
('Outer Manipur', 'Manipur', 2, 'ST', 'Churachandpur', 'ST'),
-- Arunachal Pradesh (2 seats)
('Arunachal West', 'Arunachal Pradesh', 1, 'General', 'West Kameng', NULL),
('Arunachal East', 'Arunachal Pradesh', 2, 'General', 'Changlang', NULL),
-- Nagaland (1 seat)
('Nagaland', 'Nagaland', 1, 'General', 'Kohima', NULL),
-- Mizoram (1 seat)
('Mizoram', 'Mizoram', 1, 'ST', 'Aizawl', 'ST'),
-- Sikkim (1 seat)
('Sikkim', 'Sikkim', 1, 'General', 'East Sikkim', NULL),
-- Ladakh (1 seat)
('Ladakh', 'Ladakh', 1, 'General', 'Leh', NULL),
-- Andaman and Nicobar Islands (1 seat)
('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands', 1, 'General', 'South Andaman', NULL),
-- Chandigarh (1 seat)
('Chandigarh', 'Chandigarh', 1, 'General', 'Chandigarh', NULL),
-- Dadra and Nagar Haveli and Daman and Diu (2 seats)
('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli and Daman and Diu', 1, 'ST', 'Dadra and Nagar Haveli', 'ST'),
('Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu', 2, 'General', 'Daman', NULL),
-- Lakshadweep (1 seat)
('Lakshadweep', 'Lakshadweep', 1, 'ST', 'Lakshadweep', 'ST'),
-- Puducherry (1 seat)
('Puducherry', 'Puducherry', 1, 'General', 'Puducherry', NULL);